#!/bin/sh

### BEGIN INIT INFO
# Provides:        night-watchman
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start NTP daemon
### END INIT INFO

# To enable this script:
#    sudo update-rc.d night-watchman defaults

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/local/night-watchman/run
PIDFILE=/var/run/night-watchman.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/night-watchman ]; then
    . /etc/default/night-watchman
fi


RUNASUSER=pi

case $1 in
    start)
        log_daemon_msg "Starting Night Watchman server" "night-watchman"
          start-stop-daemon --start --quiet --oknodo \
                        --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON
        status=$?
        log_end_msg $status
        ;;
    stop)
        log_daemon_msg "Stopping Night Watchman server" "night-watchman"
          start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        log_end_msg $?
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
        exit 3
        ;;
    status)
        status_of_proc $DAEMON "Night Watchman server"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
