#!/bin/bash

if [ -d .git ]; then
    git pull
fi

LOCAL_INSTALL_PATH=`dirname $0`

REPO=https://bintray.com/artifact/download/mnclimbingcoop/maven

ARTIFACT=night-watchman
GROUP=com.mnclimbingcoop
VERSION=0.8.5

GROUP_PATH=${GROUP/\./\/}
JAR=${ARTIFACT}-${VERSION}.jar

LOCAL_FOLDER=${LOCAL_INSTALL_PATH}/.${ARTIFACT}
JAR_PATH=${LOCAL_FOLDER}/${JAR}

JAVA_OPTS='-server -Xms512m -Xmx512m'

LOG_FOLDER=/var/log
LOG_FILE="${LOG_FOLDER}/${ARTIFACT}.log"

if [ -w ${LOG_FOLDER} ] || [ -w ${LOG_FILE} ] ; then
    touch ${LOG_FILE}
else
    LOG_FILE="&1"
fi

if [ ! -d ${LOCAL_FOLDER} ]; then
    mkdir -p ${LOCAL_FOLDER}
fi

if [ ! -r ${JAR_PATH} ]; then
    echo "Downloading ${REPO}/${GROUP_PATH}/${ARTIFACT}/${VERSION}/${JAR} to ${JAR_PATH}"
    curl -L ${REPO}/${GROUP_PATH}/${ARTIFACT}/${VERSION}/${JAR} > ${JAR_PATH}
fi

if [ ! -f ${LOCAL_INSTALL_PATH}/application.properties ]; then
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
    echo "!! ${LOCAL_INSTALL_PATH}/application.properties not found. !!" 1>&2
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
    echo "" 1>&2
    echo "Running application with DEFAULTS. (This will probably not work)" 1>&2
    echo "" 1>&2
fi

if [ ! -f ~/.aws/credentials ]; then
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
    echo "!! ${HOME}/.aws/credentials not found. Please configure. !!" 1>&2
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 1>&2
    echo "" 1>&2
    exit 1
fi

if [ -r ${JAR_PATH} ]; then
    echo "Executing: java -jar ${JAR_PATH}"
    pushd ${LOCAL_INSTALL_PATH}
    if [ "${LOG_FILE}" == "&1" ]; then
        java ${JAVA_OPTS} -jar ${JAR_PATH}
    else
        echo "Logging output to $LOG_FILE"
        java ${JAVA_OPTS} -jar ${JAR_PATH} >> ${LOG_FILE} 2>&1
    fi
    popd
    echo $?
else
    echo "Unable to find ${JAR_PATH}" 1>&2
fi

